common/models/Payment.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "payment".
 *
 * @property int $id_payment
 * @property int|null $id_patient
 * @property int $	N_tranf
 * @property float $value
 * @property float $amount
 * @property string $coin
 * @property string $type
 * @property string $payment_type
 * @property string $update_at
 * @property string $create_at
 * @property string $state
 * @property int|null $id_query
 * @property string $interva
 * @property string $manage_many_times
 * @property string $experation_date
 * @property int|null $id_precarious
 * @property float $unit_price
 * @property float $total_price
 * @property string $code
 * @property int $qt
 * @property string $description
 *
 * @property Precarious $precarious
 */
class Payment extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'payment';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_patient', 'id_query', 'id_precarious', 'qt'], 'integer'],
            [['value', 'amount', 'coin', 'payment_type', 'update_at', 'create_at', 'state', 'interva', 'manage_many_times', 'experation_date', 'unit_price', 'total_price','description'], 'required'],
            [['value', 'amount', 'unit_price', 'total_price'], 'number'],
            [['update_at', 'create_at'], 'safe'],
            [['coin', 'payment_type', 'manage_many_times', 'experation_date', 'code'], 'string', 'max' => 255],
            [['state'], 'string', 'max' => 11],
            [['interva'], 'string', 'max' => 30],
            [['description','type'], 'string', 'max' => 655],
            [['id_precarious'], 'exist', 'skipOnError' => true, 'targetClass' => Precarious::className(), 'targetAttribute' => ['id_precarious' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_payment' => 'Id Payment',
            'id_patient' => 'Id Patient',
            'value' => 'Value',
            'amount' => 'Amount',
            'coin' => 'Coin',
            'payment_type' => 'Payment Type',
            'update_at' => 'Update At',
            'create_at' => 'Create At',
            'state' => 'State',
            'id_query' => 'Id Query',
            'interva' => 'Interva',
            'manage_many_times' => 'Manage Many Times',
            'experation_date' => 'Experation Date',
            'id_precarious' => 'Id Precarious',
            'unit_price' => 'Unit Price',
            'total_price' => 'Total Price',
            'code' => 'Code',
            'qt' => 'Qt',
            'description' => 'Description',
        ];
    }

    /**
     * Gets query for [[Precarious]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPrecarious()
    {
        return $this->hasOne(Precarious::className(), ['id' => 'id_precarious']);
    }
    public function getPatients()
    {
        return $this->hasOne(Patient::className(), ['id_patient' => 'id_patient']);
    }
}

backend/controllers/PaymentController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Payment;
use common\models\PatientState;
use common\models\PaymentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\Pagination;
use common\models\PaymentState;
use Mpdf\Mpdf;
use \common\mail\layouts\CriarEmail;


class PaymentController extends Controller
{
   
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    public function beforeAction($action)
    {
        if (in_array($action->id, array('delete'))) {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    
    public function actionIndex()
    {
        $searchModel = new PaymentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $item_numbers = Yii::$app->request->get('item_numbers');
        $payment = Payment::find()->orderBy(['create_at'=>SORT_DESC ]);
        $countQuery = clone $payment;

        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSizeLimit' => [$item_numbers, $item_numbers]]);
        $payment = $payment->offset($pages->offset)->limit($pages->limit)->all();
        $model = new Payment();
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'payment' => $payment,
            'model'=>$model,
            'total' => $countQuery->count(),
            'item_numbers' => $item_numbers
        ]);
    }

    
    public function actionView($id)
    {
        $notificacao = \common\models\Notification::find()->where(['tables'=>'pagamento','id_conteudo'=>$id])->one();
        if (@$notificacao->state== 1){
        $notificacao->state = 2;
        $notificacao->save(false);
        }

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
        
    }
    
    public function actionCriar($id)
    {
       
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) ) 
        {
           /* if($model->qt){
               
                $parcarious = \common\models\Precarious::find()->where(['code'=>$model->code])->one();
              
                $model = new PaymentState();
                $model->state = 1;
                $model->preco = $parcarious->price;
                $model->code = $parcarious->code;
                $model->save(false);
                //$this->sendMessagePayment($model);
                return $this->redirect(['update', 'id' => $model->id_payment]);
                
            }*/
            $model->update_at=date('y-m-d H:m:i');
            $model->save(false);
            return $this->redirect(['view', 'id' => $model->id_payment]);
        }
         
        return $this->render('form', [
            'model' => $model,
        ]);
    }

    public function actionAdcionar($id)
    {

        die(var_dump($id));
       
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) ) 
        {
            $model->update_at=date('y-m-d H:m:i');
            $model->save(false);
            return $this->redirect(['criar', 'id' => $model->id_payment]);
        }
         
        return $this->render('form', [
            'model' => $model,
        ]);
    }

 
    public function actionCreate()
    {
        $model = new Payment();

        if ($model->load(Yii::$app->request->post()) ) {

          
            
            $model->create_at=date('y-m-d H:m:i');
            $model->state= 1;

            if($model->interva == 4){
                $model->interva= 4;
            }
            
            if($model->type == 'Recibo'){
                
                if($model->save(false)){

                     
                    $PatientState = PatientState::find()->where(['id_patient'=> $model->id_patient])->one();
                    
                    if($PatientState->state == 3){
                        $PatientState->state = 8;
                        $PatientState->id_payment= $model->id_payment;
                        $PatientState->save(false);
                    } elseif($PatientState->state == 16){
                        $PatientState->state = 7;
                        $PatientState->id_payment= $model->id_payment;
                        $PatientState->save(false);
                    }else{
                        $PatientState->state = $PatientState->state;
                        $PatientState->id_payment= $model->id_payment;
                        $PatientState->save(false);
                    }

                    //notificaco
                    $notificacao = new \common\models\Notification();
                    $notificacao->tables = 'pagamento';
                    $notificacao->id_conteudo= $model->id_payment;
                    $notificacao->titile = 'pagamento';
                    $notificacao->create_at = date('y-m-d');
                    $notificacao->state = 1;
                    $notificacao->save(false);
                }
            }
            $model->save(false);
            //$this->sendMessagePayment($model);
            return $this->redirect(['criar', 'id' => $model->id_payment]);
        }

        $html = $this->render('create', [
            'model' => $model,
        ]);
        return  str_replace('../biblioteca/vendor/jquery/dist/jquery.min.js','', $html);
    }

    
    public function actionUpdate($id)
    {
       
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) ) 
        {
            if($model->qt){
               
                $parcarious = \common\models\Precarious::find()->where(['code'=>$model->code])->one();
              
                $model = new PaymentState();
                $model->state = 1;
                $model->preco = $parcarious->price;
                $model->code = $parcarious->code;
                $model->save(false);
                //$this->sendMessagePayment($model);
                return $this->redirect(['update', 'id' => $model->id_payment]);
                
            }
            $model->update_at=date('y-m-d H:m:i');
            $model->save(false);
            return $this->redirect(['view', 'id' => $model->id_payment]);
        }
         
        return $this->render('update', [
            'model' => $model,
        ]);
    }

   
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }


    protected function findModel($id)
    {
        if (($model = Payment::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    public function actionBaixar($id){
        //$user = User::find()->where(['id'=>Yii::$app->user->identity->id])->one();
        $model = $this->findModel($id);
        //$model= Query::find()->one();
        $pdf_content = $this->renderPartial('recibo',[
        'model' => $model, 
        //'user' => $user,
        'type'=> 'download'
        ]);
        $mpdf = new Mpdf;
        $mpdf->WriteHTML($pdf_content);
        $mpdf->Output();
        exit;
    }

    private function sendMessagePayment($model){
        $to[] = 'edson.eng.info@gmail.com';
    //$to[] = info@waoempleos.com;
    $from = "Cenorf.com<edson.eng.info@gmail.com>";
    $ficheiros = [];
    $subject = 'Pago';
    $view =
        '<div  style="padding:0%; color:#222;">
            <p>'.$model->amount.'</p>
            <p>'.$model->value.'</p>
            <p>'.$model->type.'</p>
            <p>'.yii::t('app','Assunto').' - <strong style="color:#222; font-weight:600; font-size:18px;">'.$model->coin.'</strong></p>
            <p>'.yii::t('app','Mensagem').'<br><strong style="color:#222; font-weight:600; font-size:18px;">'.$model->create_at.'</strong></p>
        </div>';
    $emails = new CriarEmail($subject, $view);
    $emails->send($to[0], 'edson.eng.info@gmail.com>',['edson.eng.info@gmail.com>'=>'edson.eng.info@gmail.com>'], [],$ficheiros);
    }

    private function sendMessage($model)
       {

           $to = ["info@empregos.cv"];

           $from = "Empregos.cv<info@empregos.cv>";
           $ficheiros = [];

           $subject = "Registo de um nova Pedido de empregada na plataforma Empregos.CV " . $model->nome;

           $view =
               '<div  style="padding:0%; color:#222;">
               <p>Registo de um novo Pedido de serviços domesticos' . $model->nome. '</strong> na plataforma empregos.CV<br><br></p>

           <p>
               <a href="https://dev.empregos.cv/admin/index.php?r=procura/empregada" style="background:#39f; padding:6px 12px; border-radius:4px; color:#fff; text-decoration:none;">Ver empregada aqui</a>
               <br>
           </p>
       </div>';
           $emails = new CriarEmail($subject, $view);
           $emails->send($to, 'info@empregos.cv', ['info@empregos.cv' => 'Empregos.cv'], [], $ficheiros);
       }

}

backend/views/payment/_form.php
<?php
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    use kartik\select2\Select2;
    use yii\helpers\ArrayHelper;
    use common\models\Patient;
    use yii\helpers\Url;
?>
<div class="payment-form">
    <?php $form = ActiveForm::begin(
         [
            //'action'=>'/sistmagcnf/admin/payment/create'
        ]
    ); ?>
    <div class="row">
        <div class="col-sm-6">
            <label for="" class="type-label">Nome de paciente<span class="text-danger">*</span></label>
            <div class="form-group">
                <?=  $form->field($model, 'id_patient')->widget(Select2::classname(), [
                    'data' => ArrayHelper::map(Patient::find()->orderBy(['create_at' => SORT_DESC,])->all(), 'id_patient', 'name'),
                    'language' => 'en',
                    'options' => ['placeholder' => 'Selecionar Paciente'],
                    'pluginOptions' => [
                    'allowClear' => true,
                    'class' => 'form-control  ',
                    'required' => true,
                    'data-msg' => 'Por favor Selecionar Paciente.',
                    'data-error-class' => 'u-has-error',
                    'data-success-class' => 'u-has-success',
                    ],
                ])->label(false) ?>
            </div>
        </div>
        <div class="col-sm-6">
            <label for="" class="type-label">type<span class="text-danger">*</span></label>
            <?= $form->field($model, 'type')->dropDownList(
                  [
                      'Recibo' => 'Recibo',
                      'Proforma' => 'Proforma',
                  ],
                  [
                      'class' => 'form-control custom-select',
                      'data-msg' => 'Selecionar typy',
                      'require' =>true,
                      'data-error-class' => 'u-has-error',
                      'data-success-class' => 'u-has-success',
                      'prompt' => 'Selecionar forma de pagamento'
                  ]
            )->label(false) ?>

        </div>
        <div class="col-sm-4">
            <label for="" class="type-label">Nº de Prestações<span class="text-danger">*</span></label>
            <?= $form->field($model, 'interva')->dropDownList(
                  [
                      '1' => 'Primeiro Parcela',
                      '2' => 'Segundo Parcela',
                      '3' => 'Terceiro Parcela',
                      '4' => 'Completo',

                  ],
                  [
                      'class' => 'form-control custom-select',
                      
                      'data-msg' => 'Selecionar modo de pagamento',
                      'data-error-class' => 'u-has-error',
                      'data-success-class' => 'u-has-success',
                      'prompt' => 'Selecionar modo de pagamento'
                  ]
              )->label(false) ?>
        </div>
        <div class="col-sm-4">
            <label for="" class="type-label">Pag. Referente a:<span class="text-danger">*</span></label>
            <?= $form->field($model, 'payment_type')->dropDownList(
                  [
                      'Dinheiro' => 'Dinheiro',
                      'Vinte 24' => 'Vinte 24',
                      'Cheque' => 'Cheque',
                      'Transferencia' => 'Tranferencia',
                      'Financimento' =>'Financiamento',
                  ],
                  [
                      'class' => 'form-control custom-select',
                      
                      'data-msg' => 'Selecionar forma de Pagamento',
                      'data-error-class' => 'u-has-error',
                      'data-success-class' => 'u-has-success',
                      'prompt' => 'Selecionar forma de pagamento'
                  ]
              )->label(false) ?>

        </div>
        <div class="col-sm-4">
            <label for="" class="type-label">Nº Ord. Trans</label>
            <?= $form->field($model, 'N_tranf')->textInput([
                        "class" => "form-control",
                        'placeholder' => "Introduzir Nº Ord. Trans",
                        'aria-label' => "Introduzir Nº Ord. Trans",
                        'aria-describedby' => "dataInicioLabel",
                        'data-msg' => " Introduzir Nº Ord. Trans",
                        'data-error-class' => "u-has-error",
                        'data-success-class' => "u-has-success",
                        'type' => 'number'
                ])->label(false) ?>
        </div>
    </div>
    <div class="col-sm-12 text-right">
        <div class="form-group">
            <a href="<?= Url::to(['/payment'])?> " class="btn btn-sm btn-soft-secondary rounded">Cancelar</a>

            <?= Html::submitButton($model->isNewRecord ? '<i class="far fa-save mr-2"></i>Guardar' : '<i class="far fa-save mr-2"></i>Atualizar', ['class' => $model->isNewRecord ? 'btn btn-indigo btn-sm rounded ' : 'btn btn-indigo btn-sm rounded ','id'=>'btn-save']) ?>
        </div>

    </div>

    <?php ActiveForm::end(); ?>

</div>
<style>
.type-label {
    display: block;
    /* text-transform: lowercase; */
    font-size: 80%;
    font-weight: 600;

}

.select2-container--krajee .select2-selection--single .select2-selection__arrow {
    height: 48px !important;
}

.select2-container--krajee .select2-selection--single {
    height: 50px !important;
    padding: 14px 24px 6px 16px !important;
}
</style>


<script>
$(document).on('click', '.saves', function(e) {
    e.preventDefault()
    e.stopImmediatePropagation();
    alert('ok');
    save($('#formConching'), $('#formConching')[0], 'create');
    $('input').val(" ");
    $("#datatable_users_filter label").css("display", "none");

});
</script>

backend/views/payment/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
$this->title = 'Efetuar Pagamento';

?>
<div class="Efetuar Pagamento">

    <div class="row mx-gutters-2">
        <div class="col-md-10">
        <h4 class="font-weight-bold"><?= Html::encode($this->title) ?></h4>
        </div>
        <div class="col-md-2">
            <a class="float-right " href="<?= Url::to(['/payment/index'])?>">Voltar</a>
        </div>
    </div>
    <hr>
    <div class="card">
         <div class="card-body shadow-sm p-4">
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
     </div>

</div>

backend/views/payment/preco.php
<?php
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    use kartik\select2\Select2;
    use yii\helpers\ArrayHelper;
    use common\models\Patient;
    use yii\helpers\Url;
?>
    <?php $form = ActiveForm::begin([
        'id' => 'form-formador',
        'options' => ['enctype' => 'multipart/form-data'],
            'action' => \yii\helpers\Url::to(['/payment/adcionar']),
        ]) ?>
    <div class="row">
        <div class="col-sm-4">
            <label for="" class="type-label">Quantidade<span class="text-danger">*</span></label>
            <?= $form->field($model, 'qt')->textInput([
                "class" => "form-control",
                'placeholder' => "Introduzir qt",
                'aria-label' => "Introduzir qt",
                'required' => true,
                'aria-describedby' => "dataInicioLabel",
                'data-msg' => " Introduzir qt",
                'data-error-class' => "u-has-error",
                'data-success-class' => "u-has-success",
                'type' => 'number'
            ]
            )->label(false)  ?>
        </div>
        <div class="col-sm-4">
            <label for="" class="type-label">Codigo<span class="text-danger">*</span></label>
            <?= $form->field($model, 'id_precarious')->dropDownList(ArrayHelper::map(\common\models\Precarious::find()->all(), 'id_precarious', 'code'), ['prompt'=>'','id'=>'id_precarious'] )->label(false); ?>
        </div>
        <div class="col-sm-4">
            <label for="" class="type-label">preco<span class="text-danger">*</span></label>
            <?= $form->field($model, 'qt')->textInput([
                    "class" => "form-control",
                    'placeholder' => "Introduzir qt",
                    'aria-label' => "Introduzir qt",
                    'required' => true,
                    'aria-describedby' => "dataInicioLabel",
                    'data-msg' => " Introduzir qt",
                    'data-error-class' => "u-has-error",
                    'data-success-class' => "u-has-success",
                    'type' => 'number'
                ]
                )->label(false)  ?>
        </div>
        <div class="col-sm-12 mt-2 text-right">
            <?= Html::submitButton('<i class="far fa-save mr-2"></i>Adcionar', ['class' => 'btn btn-sm btn-primary save buton_save ']) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>

backend/views/payment/recibo.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
\yii\web\YiiAsset::register($this);
?>
<div id="print" style=" font-family: 'Open Sans', sans-serif; size: 18cm 18cm;">

<div class="row mx-gutters-2">
        <div class="col-lg-6">
            <h1 class="h5 font-weight-bold"><?= $model->type?></h1>
        </div>
        <div class="col-lg-6">
            <div class="ml-lg-auto float-right">
            <a class="" href="<?= Url::to(['/payment/index'])?>">Voltar</a>
            <div class="btn-group position-relative ">

                <a id="" class="btn btn-sm btn-icon rounded " href="javascript:;" role="button"
                    aria-controls="#id" aria-haspopup="true" aria-expanded="false"
                    data-toggle="dropdown" data-unfold-event="click" data-unfold-target="#"
                    data-unfold-type="css-animation" data-unfold-duration="300"
                    data-unfold-delay="300"
                    data-unfold-animation-in="slideInUp"
                    data-unfold-animation-out="fadeOut" style="width: 2.6rem; height: 2.6rem;">
                    <span class="fas fa-ellipsis-v btn-icon__inner"></span>
                </a>

                <div id="" class="dropdown-menu dropdown-unfold dropdown-menu-right" aria-labelledby="id-invoker">
                    <?= Html::a('<i class="fas fa-briefcase mr-1"></i>Imprimir', ['imprimirr'], ['class' => 'dropdown-item transition-3d-hover open-modal' ,'target'=>"_blank"]) ?>   
                </div>
                </div>
            </div>
         </div>
    </div>
   
    <hr>

  
        <div class="card bg-img-hero" style="background-image: url(../../biblioteca/svg/components/bg-elements-6.svg);">
          <div class="card-body p-4 p-md-7 p-lg-11">
            <div class="row justify-content-lg-between align-items-sm-center ">
              <div class="col-sm-6 col-lg-4 order-sm-2 text-sm-right  mb-sm-0">
                <h1 class="h2 font-weight-medium mb-0 mt-20">
                    <?php if($model->type == 'Recibo'):?>
                      Fatura#<br>
                       Recibo
                    <?php elseif($model->type == 'Proforma'):?>
                      Proforma
                    <?php endif;?>
                </h1>
              </div>

              <div class="col-sm-5 order-sm-1">
                <!-- Logo -->
                <div class="media align-items-center d-block mb-3">
                    <span class="u-sm-avatar">
                        <img class=" rounded" src="../../recurso/img/Logo.jpg" alt="Image Description" style="height: 80px; width: 100px;">
                    </span>
                    <span>CENORF.- CP 26-C</span>
                </div>
                <!-- End Logo -->
                <!-- Address -->
                
                <span class="d-block"> <small class="mr-2 font-weight-bold font-weight-normal"><b>Sede:</b></small><small class=" text-muted">Praia, A.S. Filipe - Cabo Verde</small></span>
                <span class="d-block"><small class="mr-2 font-weight-bold font-weight-normal"><b>Contacto:</b></small><small class="text-muted">264 76 9 - 5157145</small></span>
                <span class="d-block"><small class="mr-2 font-weight-bold font-weight-normal"><b>Email:</b></small><small class="text-muted">cenorf@sapo.cv</small></span>
                <span class="d-block"><small class="mr-2 font-weight-bold font-weight-normal"><b>NIF:</b></small><small class="text-muted">93423246</small></span>
                <span class="d-block"><small class="mr-2 font-weight-bold font-weight-normal"><b>Nº Conta(BCA):</b></small><small class="text-muted">74589703102</small></span>
                <!-- End Address -->
              </div>
              
            </div>
            <hr style="border:1px solid #e7eaf3!important;" class="mb-4">
            

            <!-- Bill To -->
            <div class="row justify-content-md-between mb-7">
              <div class="col-sm-12">
                <?php if($model->patients):?>
                <span class="font-weight-normal text-uppercase"><?=$model->patients->name?></span>
                <?php endif;?>
              </div>
              <div class="col-sm-7">
                <span class="d-block "><small class="mr-2 font-weight-normal "><?= yii::t('app', 'Data') ?>:</small><small class="font-weight-normal "><?= $model->create_at?></small><span>
              </div>

              <div class="col-md-7 col-lg-4 text-right">
                <span class="d-block"><small class="mr-2 font-weight-normal "><?= yii::t('app', 'Nº') ?></small><small class="font-weight-normal "><?=$model->id_payment?>/<?=  Yii::$app->formatter->asDate('now', 'yyyy-MM-dd');?></small><span>
              </div>
              <div class="col-sm-6">
                <span class="d-block"><small class="mr-2 font-weight-normal "><?= yii::t('app', 'Nif') ?>:</small><small class="font-weight-normal ">87676655545</small><span>
              </div>

              <div class="col-sm-6 text-right">
                <span class="d-block"><small class="mr-2 font-weight-normal "><?= yii::t('app', 'pgt') ?></small><small class="font-weight-normal ">imprisão</small><span>
              </div>
              
            </div>
            <!-- End Bill To -->

            <!-- Table -->
            <table class="table table-heighlighted font-size-1 mb-9">
              <thead class="top">
                <tr class="text-secondary">
                  <th scope="col" class="font-weight-bold"><?= yii::t('app', 'Qtd') ?></th>
                  <th scope="col" class="font-weight-bold"><?= yii::t('app', 'Descrição') ?></th>
                  <th scope="col" class="font-weight-bold"><?= yii::t('app', 'Preço') ?></th>
                  <th scope="col" class="font-weight-bold text-right"><?= yii::t('app', 'Total') ?></th>
                </tr>
              </thead>
              <tbody>

                <tr>
                  <td scope="row" class="font-weight-normal">10 </td>
                  <td>fgdhg dhjdfgjkg dmdjfjgbdmfjhjf dnhfdjf dhhdf </td>
                  <td>20</td>
                  <td class="text-right">30000Esc</td>
                </tr>

              </tbody>
              <tfoot>
                <tr class="h6">
                  <td colspan="2" class="text-right font-weight-bold">Subtotal</td>
                  <td colspan="3" class="text-right">30000Esc</td>
                </tr>
                <tr class="h6">
                  <td colspan="2" class="text-right font-weight-bold">Desconto</td>
                  <td colspan="3" class="text-right">0Esc</td>
                </tr>

                <tr class="h6">
                  <td colspan="2" class="text-right font-weight-bold">Total</td>
                  <td colspan="3" class="text-right">30000Esc</td>
                </tr>

              </tfoot>
            </table><br><br>
            
            <div class="row">
              <div class="col-md-12 col-lg-12 order-md-1 align-self-end text-center">
              <span>_________________________</span>
                <h3 class=" mb-0 font-weight-bold">Assinatura</h3>
                
              </div>
            </div><br><br><br><br>
            <!-- End Table -->
            <hr style="border:1px solid #e7eaf3!important;" class="">
            <!-- Contacts -->
            <div class="row">
              <div class="col-md-12 col-lg-12 order-md-1 align-self-end text-center">
                <p class="small text-muted mb-0">&copy; Documento processado por computador</p>
              </div>
            </div>
            <!-- End Contacts -->
          </div>
        </div>
        </div>
        <?php if( @$type == 'preview' ): ?>

<script src="/js/jQuery.print.js"></script>
<script>
    function print() {
        //Print ele4 with custom options
        $("#print").print({
            //Use Global styles
            globalStyles: false,
            //Add link with attrbute media=print
            mediaPrint: false,
            //Custom stylesheet
            stylesheet: "https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i",
            // bootstrap: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css",
            // fontawesome: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.css",
            //Print in a hidden iframe
            iframe: true,
            //Don't print this
            // noPrintSelector: ".avoid-this",
            //Add this at top
            prepend: "EMPREGOSCV",
            //Add this on bottom
            append: "GERADO EM EMPREGOS.CV",
            //Log to console when printing is done via a deffered callback
            deferred: $.Deferred().done(function () {
                console.log('Printing done', arguments);
            })
        });
    }
</script>

<?php endif; ?>
    
<style>

.foter {
    position: absolute;
    bottom: -20px;
    width: 100%;
    background: white;
}

  .mt-20 {
    margin-top: 11rem !important;
}
.table-heighlighted tfoot td {
    border-top: 2px solid #e7eaf3!important; 
}



</style>

backend/views/payment/update.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Atualizar Pagamento' . $model->id_payment;

?>
<div class="payment-update">

    <div class="row mx-gutters-2">
        <div class="col-md-10">
        <h4 class="font-weight-bold"><?= Html::encode($this->title) ?></h4>
        </div>
        <div class="col-md-2">
            <a class="float-right " href="<?= Url::to(['/payment/index'])?>">Voltar</a>
        </div>
    </div>
    <hr>
    <div class="card">
         <div class="card-body shadow-sm p-4">
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
     </div>

</div>