common/models/Calendar.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "calendar".
 *
 * @property int $id_calendar
 * @property int|null $id_patient
 * @property int $id_employees
 * @property int id_query
 * @property string $update_at
 * @property string $data
 * @property string $created_at
 * @property string $name_patient
 * @property string $type
 * @property string $state
 * @property string $name
 * @property string $hora_inicio
 * @property string $hora_fim
 */
class Calendar extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'calendar';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_patient', 'id_employees','id_query'], 'integer'],
            //[['id_employees', 'update_at', 'date', 'created_at', 'state', 'name'], 'required'],
            [['update_at', 'data', 'created_at', 'state'], 'safe'],
            [['name','hora_inicio','hora_fim','name_patient','type'], 'string', 'max' => 300],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_calendar' => 'Id Calendar',
            'id_patient' => 'Id Patient',
            'id_employees' => 'Id Employees',
            'update_at' => 'Update At',
            'data' => 'Date',
            'created_at' => 'Created At',
            'state' => 'State',
            'name' => 'Name',
        ];
    }
    public function getPatients()
    {
        
        return $this->hasOne(Patient::className(), ['id_patient' => 'id_patient']);
    }

    public function getEmployes()
    {
        
        return $this->hasOne(Employees::className(), ['id_employees' => 'id_employees']);
    }

    
}

backend/controllers/CalendarController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Calendar;
use common\models\PatientState;
use common\models\Patient;
use common\models\PaymentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


class CalendarController extends Controller
{
   
   /* public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }*/
    
    public function beforeAction($action)
    {
        if ($action->id === "calendario" || $action->id === "Avaliacao" || $action->id === "delete" || $action->id === "calendar" ) {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    public function actionCalendario(){
      
        $id_calendar = Yii::$app->request->get('id_calendar');
        $calendario = (new \yii\db\Query())->select(
            [
                "name_patient AS name_patient",
                "CONCAT(data, 'T', hora_inicio) AS start",
                "id_calendar",
                "data as date",
            ]
        )->from('calendar')->where(["id_calendar"=>$id_calendar])->all();
        // die(var_dump(json_encode($calendario)));
       
        return json_encode($calendario);
        //$html = str_replace(Yii::$app->params['jquery'], '', $html);
        //return $html;
    }

    public function actionAvaliacao(){

        $id_calendar = Yii::$app->request->get('id_calendar');
        $html = $this->renderAjax('calendar',[
            'id_calendar'=>$id_calendar,
        ]);
        $html = str_replace(Yii::$app->params['jquery'], '', $html);
        return $html;
    }

    
    public function actionCalendar()
    {
       
        $calendars = Calendar::find()->where(['name'=>'avaliacao']) ->all();
         
        $html = $this->render('index', [
           'calendars' => $calendars,
        ]);
        $html = str_replace(Yii::$app->params['jquery'], '', $html);
        return $html;
    }

   


    public function actionIndex($id)
    {
      
        $notification = \common\models\Notification::find()->where(['tables'=>'fisioterapia', 'titile'=>'FTP','id_conteudo'=>$id])->one();
        if (@$notification) {
            $notification->delete();
        }
        $html =  $this->render('index', []);
        $html = str_replace(Yii::$app->params['jquery'], '', $html);
        return $html;
    }
    public function actionCreate()
    {
        $model = new Calendar();

        $tipo = Yii::$app->request->get('tipo');
        
        if ($model->load(Yii::$app->request->post())) {
            $Patient = \common\models\Patient::find()->where(['id_patient'=> $model->id_patient])->one();
             $model->create_at=date('y-m-d H:m:i');
             $model->name_patient = $Patient->name;
             $model->type = $tipo;
             if($model->save(false)){               
                $PatientState = \common\models\PatientState::find()->where(['id_patient'=> $model->id_patient])->one();
                $PatientState->state = 2;
                $PatientState->id_calendar = $model->id_calendar;
                $PatientState->save(false);              
            }
            //Yii::$app->session->setFlash('error-create', yii::t('app','Foto de capa faq. Tente outra!'));
            Yii::$app->session->setFlash('success-create', "agendamento foi Realizado com sucesso.");
            return $this->redirect(['calendar']);
        }

        $html =  $this->renderAjax('create', [
            'model' => $model,
        ]);
        return str_replace('<script src="/sistmagcnf/admin/../biblioteca/vendor/jquery/dist/jquery.min.js"></script>', '', $html);

    }
    public function actionLista()
    {
       
        $calendar = Calendar::find()->all();
        return $this->render('lista', [
            'calendar' => $calendar,
            
        ]);
    }

    public function actionCall()
    {
       
        $calendar = Calendar::find()->all();
        return $this->render('lista', [
            'calendar' => $calendar,
            
        ]);
    }
}

backend/views/calendar/Calendar.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Url;
use common\models\PatientState;
use common\models\Patient;
use backend\assets\AppAsset;
$this->title =yii::t('app','Agendamento');
$urlPath = Yii::$app->params['urlPath'];
AppAsset::register($this);

?>
<div id="calendar" data-language="<?= yii::$app->language ?>" data-title-view="<?= Yii::t('app','Entrevista de trabalho com') ?>">
</div>

<?php
    $script = <<<JS
    $(document).ready(function() {
      var calendar = $('#calendar').fullCalendar({
        defaultView: 'month',
        header: {
            right: 'prev today next',
            center: 'title',
            left: 'month,agendaWeek,agendaDay'
        },
        locale: $('#calendar').attr('data-language'),
        eventSources: [
            // your event source
            {
                url: '/sistmagcnf/admin/calendar/calendario?id_calendar='+$('#calendar-select').val(),
                type: 'get',
                error: function () {
                    alert('there was an error while fetching events!');
                },
                success: function (res) {
                    console.log('ggggggggggggggggggggggggggggggggg');
                    console.log(res);
                },
                color: '#00c9a7',  // a non-ajax option
                textColor: 'white' // a non-ajax option
            },
        ],
        editable: true,
        droppable: false,
        eventResize: function (event, delta, revertFunc) {
                bootbox.confirm({
                    title: 'Alterar a hora da Entrevista?',
                    message: 'Ao efectuar essa ação o candidato será notificado a alteração da hora da entrevista',
                    //size: 'small',
                    buttons: {
                        confirm: {
                            label: 'Sim',
                            className: 'btn-success'
                        },
                        cancel: {
                            label: 'Não',
                            className: 'btn-danger'
                        }
                    },
                    callback: function (result) {

                        if (result === true) {
                            var start = event.start.format('HH:mm:SS');
                            var end = (event.end == null) ? start : event.end.format('HH:mm:SS');
                            var date = event.start.format('YYYY-MM-DD');
                            var url = "";
                            var type = 'post';
                            var formData = {
                                'hora_inicio': start,
                                'data': date,
                                'id_calendar': event.id_calendar
                            };

                            $.ajax({
                                type: type,
                                url: url,
                                data: formData,
                                dataType: 'json',
                                success: function (data) {
                                    if (data.type === 'error') {
                                        revertFunc();
                                        toastr.error(data.message, {timeOut: 5000}).css("width", "300px");
                                    }
                                    // else {
                                    //     startDashboard();
                                    // }
                                }
                            });
                        } else {
                            revertFunc();
                        }
                    }
                });
            },

      });
     console.log(calendar);
        
    });
    
JS;
$this->registerJS($script);

?>

<style>
table th {
    color: #1e2022!important;
}
</style>

backend/views/calendar/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;
use common\models\Patient;
use common\models\Employees;
?>

<div class="calendar">

    <?php $form = ActiveForm::begin(
        
    ); ?>
    <div class="row">
        <div class="col-sm-6">
            <label for="" class="type-label">Nome de Paciente<span class="text-danger">*</span></label>
            <div class="form-group">
                <?=  $form->field($model, 'id_patient')->widget(Select2::classname(), [
                        'data' => ArrayHelper::map(Patient::find()->orderBy(['create_at' => SORT_DESC,])->all(), 'id_patient', 'name'),
                        'language' => 'en',
                        'options' => ['placeholder' => 'Selecionar Paciente'],
                        'pluginOptions' => [
                        'maxlength' => true,
                        'class' => 'form-control  ',
                        'required' => true,
                        'data-msg' => 'Por favor Selecionar Paciente.',
                        'data-error-class' => 'u-has-error',
                        'data-success-class' => 'u-has-success',
                        ],
                    ])->label(false) ?>
            </div>
        </div>
        <div class="col-sm-6">
            <label for="" class="type-label">Técnico Responsavel<span class="text-danger">*</span></label>
            <div class="form-group">
                <?=  $form->field($model, 'id_employees')->widget(Select2::classname(), [
                        'data' => ArrayHelper::map(Employees::find()->orderBy(['create_at' => SORT_DESC,])->all(), 'id_employees', 'name'),
                        'language' => 'en',
                        'options' => ['placeholder' => 'Selecionar Técnico'],
                        'pluginOptions' => [
                        'maxlength' => true,
                        'class' => 'form-control  ',
                        'required' => true,
                        'data-msg' => 'Por favor Selecionar Técnico.',
                        'data-error-class' => 'u-has-error',
                        'data-success-class' => 'u-has-success',
                        ],
                    ])->label(false) ?>
            </div>
        </div>
        <div class="col-md-4">
            <label class="form-label" for="signinSrEmailExample3"><?= yii::t('app', 'Data') ?></label>

            <?= $form->field($model, 'data')->textInput([
                      "class" => "form-control input_date",
                      'placeholder' => "Data nascimento",
                      'aria-describedby' => "dataInicioLabel",
                      'data-error-class' => "u-has-error",
                      'data-success-class' => "u-has-success",
                      'data-rp-date-format' => "Y-m-d",
                      'type' => 'date'
                ])->label(false) ?>
        </div>
        <div class="col-md-4">
            <label class="form-label" for="signinSrEmailExample3"><?= yii::t('app', 'Hora Inicio') ?></label>
            <?= $form->field($model, 'hora_inicio')->textInput(['type' => 'time', 'class'=>'form-control-sm form-control','id' => 'hora_inicio'])->label(false) ?>
        </div>
        <div class="col-md-4">
            <label class="form-label" for="signinSrEmailExample3"><?= yii::t('app', 'Hora Fim') ?> </label>
            <?= $form->field($model, 'hora_fim')->textInput(['type' => 'time','class'=>'form-control-sm form-control','id' => 'hora_fim'])->label(false)?>
        </div>
    </div>
    <div class="col-sm-12 text-right">
        <div class="form-group">
            <button type="button" class="btn btn-sm rounded btn-soft-secondary transition-3d-hover" data-dismiss="modal"
                style="margin-right: 5px;"><i class="fa fa-times mr-1"></i><?= Yii::t('app', 'Cancelar') ?></button>
            <?= Html::submitButton($model->isNewRecord ? '<i class="far fa-save mr-2"></i>Guardar' : '<i class="far fa-save mr-2"></i>Atualizar', ['class' => $model->isNewRecord ? 'btn btn-indigo btn-sm rounded ' : 'btn btn-indigo btn-sm rounded ','id'=>'btn-save']) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>
<style>
.select2-container--krajee .select2-selection--single .select2-selection__arrow {
    height: 48px !important;
}

.select2-container--krajee .select2-selection--single {
    height: 50px !important;
    padding: 14px 24px 6px 16px !important;
}

.flatpickr-current-month {
    padding: 0px !important;
}

.flatpickr-months {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    /* display: flex; */
    position: relative;
    background-color: #2d1582;
    border-top-left-radius: 0.25rem;
    border-top-right-radius: 0.25rem;
    padding: .75rem;
}

span.cur-month {
    color: #fff !important;
}

.numInputWrapper {
    color: #fff !important;
}

svg {
    fill: rgba(255, 255, 255, 0.7);
}

.flatpickr-day.today {
    border-color: #959ea9;
}

.flatpickr-day.today {
    border-color: #2d1582 !important;
}
</style>

backend/views/calendar/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
?>
<div class="calendar">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

backend/views/calendar/index.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Url;
use common\models\PatientState;
use common\models\Patient;
use common\models\Calendar;
use backend\assets\AppAsset;
$this->title =yii::t('app','Agendamento');
$urlPath = Yii::$app->params['urlPath'];
AppAsset::register($this);

?>
<div class="row mb-2">
    <div class="col-sm-6">
        <a href="#" class="btn btn-nr btn-indigo font-weight-bold open-modal" id="anucio_automatico"
            data-modal-size="modal-lg" data-url="<?= Url::to(['create']) ?>"
            data-title="<?= Yii::t('app', 'Agenda') ?>">
            <?= Yii::t('app', 'Marcar Agenda') ?>
        </a>

    </div>
    <div class="col-md-6 text-right">
        <h4 class="font-weight-bold">Agenda de avaliação</h4>
    </div>
</div>

<div class="card">
    <div class="shadow-soft bg-white">
        <div class="py-4 px-0 mx-4 model-lg">
            <div class="row mx-gutters-2 justify-content-sm-between">

                <div class="col-lg mb-lg-0">
                    <h5 class="font-weight-normal h6"><?= yii::t('app', 'Filtrar por paciente') ?></h5>
                </div>
                <div class="col-lg ml-2 has-success">
                    <?php
                        $patientList = yii\helpers\ArrayHelper::map(Calendar::find()->orderBy(['create_at' => SORT_DESC,])->all(), 'id_calendar', 'name_patient');
                        echo yii\helpers\Html::dropDownList('calendar-select', null, $patientList, [
                            'id' => 'calendar-select',
                            'class' => 'form-control form-control-sm'
                        ]);
                    ?>
                </div>


            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="loader" style="display:none; padding: 15px;"><img src="/img/loading.gif" /></div>
        <div class="load-calendar"></div>
    </div>
    <div id="calendar" data-language="<?= yii::$app->language ?>"
        data-title-view="<?= Yii::t('app','Entrevista de trabalho com') ?>">
    </div>
</div>

<?php
    $script = <<<JS

    var id_calendar = $('#calendar-select').val();
    $('.load-calendar').load("/sistmagcnf/admin/calendar/avaliacao?id_calendar=" + id_calendar);

    $(document).on('change', '#calendar-select', function() {
            var id_calendar = $(this).val();
        $('.load-calendar').load("/sistmagcnf/admin/calendar/avaliacao?id_calendar=" + id_calendar);
    });

JS;
$this->registerJS($script);

?>

backend/views/calendar/lista.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\LinkPager;


?>



<div class="employees-index mt-6">
<?php if (Yii::$app->session->hasFlash("success-create")): ?>
<div class="alert-success alert alert-dismissible fade show" role="alert">
    <?= Yii::$app->session->getFlash("success-create") ?>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<?php endif; ?>
  <div class="row mb-3">
    <div class="col-sm-6">
        
    </div>
    <div class="col-sm-6">
        <form role="search" class="app-search">
            <div class="form-group mb-0">
                <input type="text" class="form-control input-searc"  placeholder="Search..">
                <button type="submit" class="buton-search"><i class="fa fa-search icon-seach"></i></button>
            </div>
        </form>
    </div>
  </div>
    <table class="table">
        <thead class="top">
            <tr>
            <th scope="col">Nome de Paciente</th>
            <th scope="col">Técnico Responsável</th>
            <th scope="col">ACtividade</th>
            <th scope="col">Data</th>
            <th scope="col">Hora inicio</th>
            <th scope="col">Hora fim</th>
            <th scope="col">Opção</th>

            </tr>
        </thead>
        <tbody>
            <?php  foreach ($calendar as $calendars) { ?>
                <tr>
                    <td><?= $calendars->patients->name?></td>
                    <td><?= $calendars->employes->name?></td>
                    <td><?= $calendars->name ?></td>
                    <td><?= $calendars->date?></td>
                    <td><?= $calendars->hora_inicio?></td>
                    <td><?= $calendars->hora_fim?></td>
                <td> 
                    <?= Html::a('<i class="fas fa-eye btn-soft-secondary dropdown-item-icon"></i>', ['views', 'id' => $calendars->id_calendar], ['class' => '']) ?>     
                </td>
                </tr>
            <?php }?>  
        </tbody>
    </table>



</div>
<style>
    .btn-nr{
      padding: 0.625rem 1.125rem;
    font-size: 0.875rem;
    line-height: 1.5;
    }

    .input-searc{
      border: 1px solid #e0e0ea;
    font-size: 13px;
    height: 34px;
    padding-left: 18px;
    padding-right: 40px;
    margin-right: 16px;
    background: #e0e0ea;
    -webkit-box-shadow: none;
    box-shadow: none;
    border-radius: 30px;
    
    }
    .buton-search{
      position: absolute;
    top: 10px;
    right: 26px;
    display: block;
    color: #9ca8b3;
    font-size: 11px;
    border: none;
    background-color: transparent;
    }
    .btn-nr {
      color: #fff;
     
    font-size: 0.875rem;
    }
   
    
</style>