common/models/User.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $username
 * @property string $auth_key
 * @property string $imagem
 * @property string $password_hash
 * @property string|null $password_reset_token
 * @property string $email
 * @property string $type_user
 * @property string $morada
 * @property string $contacto
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property string|null $verification_token
 */
class User extends  \yii\db\ActiveRecord implements \yii\web\IdentityInterface
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            //[['username','email'], 'required'],
            [['status' ,'created_at', 'updated_at'], 'integer'],
            [['username', 'password_hash', 'password_reset_token', 'email', 'verification_token'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['imagem','username','email','type_user','contacto','morada'], 'string', 'max' => 400],
            [['username'], 'unique'],
            [['email'], 'unique'],
            [['password_reset_token'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'auth_key' => 'Auth Key',
            'password_hash' => 'Password Hash',
            'password_reset_token' => 'Password Reset Token',
            'email' => 'Email',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'verification_token' => 'Verification Token',
        ];
    }
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }
    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'valido' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

backend/controllers/UsersController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\User;
use common\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \common\models\UploadHandler;
use frontend\models\ChangePasswordForm;

/**
 * UserController implements the CRUD actions for User model.
 */
class UsersController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function beforeAction($action)
    {
        if (in_array($action->id, array('delete'))) {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
         $user = User::find()->all();
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'user' =>  $user
        ]);
    }

    public function actionPerfil($id)
    {
        $users = User::find()->where(['id'=>$id])->one();
        return $this->render('perfil', [
            'users' =>  $users
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post())) {
            if ($_FILES['image-user'] /*&& $_FILES['image-capa']['name'] != $capa['original_name']*/) {
                $file = new UploadHandler('image-user');
                if ($file->validate()) {
                    // salvar foto
                    $uploaded = $file->upload('imgUtilizador', true);
                    //setcookie('cur_cap', serialize($uploaded), time() + 50000, '/');
                    $model->image = $uploaded['full_path'];
                } else {
                    Yii::$app->session->setFlash('error-create', "Foto de perfil invalida. Tente outra!");
                }
            }
            $model->create_at=date('y-m-d H:m:i');
            $model->status= 1;
            $model->save(false);
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            if ($_FILES['image-user'] /*&& $_FILES['image-capa']['name'] != $capa['original_name']*/) {
                $file = new UploadHandler('image-user');
                if ($file->validate()) {
                    // salvar foto
                    $uploaded = $file->upload('imgUtilizador', true);
                    //setcookie('cur_cap', serialize($uploaded), time() + 50000, '/');
                    $model->imagem = $uploaded['full_path'];
                } else {
                    Yii::$app->session->setFlash('error-create', "Foto de perfil invalida. Tente outra!");
                }
            }
            $model->updated_at=date('y-m-d H:m:i');
            $model->status= 1;
            $model->save(false);
            Yii::$app->session->setFlash('success-create', "Utilizador foi Atualizado com sucesso.");
            return $this->redirect(['view', 'id' => $model->id]);
        }

        $html = $this->renderAjax('update', [
            'model' => $model,
        ]);

        return str_replace('<script src="/sistmagcnf/admin/../biblioteca/vendor/jquery/dist/jquery.min.js"></script>', '', $html);
    }

    public function actionUpdates($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            if ($_FILES['image-user'] /*&& $_FILES['image-capa']['name'] != $capa['original_name']*/) {
                $file = new UploadHandler('image-user');
                if ($file->validate()) {
                    // salvar foto
                    $uploaded = $file->upload('imgUtilizador', true);
                    //setcookie('cur_cap', serialize($uploaded), time() + 50000, '/');
                    $model->imagem = $uploaded['full_path'];
                } else {
                    Yii::$app->session->setFlash('error-create', "Foto de perfil invalida. Tente outra!");
                }
            }
            $model->updated_at=date('y-m-d H:m:i');
            $model->status= 1;
            $model->save(false);
            Yii::$app->session->setFlash('success-create', "Utilizador foi Atualizado com sucesso.");
            return $this->redirect(['perfil', 'id' => $model->id]);
        }

        $html = $this->renderAjax('form', [
            'model' => $model,
        ]);

        return str_replace('<script src="/sistmagcnf/admin/../biblioteca/vendor/jquery/dist/jquery.min.js"></script>', '', $html);
    }

    public function actionEditar($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            $model->save(false);
            Yii::$app->session->setFlash('success-create', "Palavra passe foi Atualizado com sucesso.");
            return $this->redirect(['perfil', 'id' => $model->id]);
        }

        $html = $this->renderAjax('editar', [
            'model' => $model,
        ]);

        return str_replace('<script src="/sistmagcnf/admin/../biblioteca/vendor/jquery/dist/jquery.min.js"></script>', '', $html);
    }

    public function actionDifinicao()
    {
        $modelUser = User::find()->where(['id'=>Yii::$app->user->identity->id])->one();
        $html = $this->render('difinicao', [
            'modelUser' => $modelUser
        ]);

        return str_replace('<script src="/sistmagcnf/admin/../biblioteca/vendor/jquery/dist/jquery.min.js"></script>', '', $html);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->session->setFlash('error', "Utilizador foi Eliminado com sucesso.");
        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionMudar()
    {
        try {

            if (Yii::$app->user->isGuest) {
                return $this->redirect('/site/login');
            }

            $model = new ChangePasswordForm();

            if (Yii::$app->request->isAjax) {
                if ($_POST) {
                    if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->changePassword()) {
                        return json_encode([
                            'status' => 'success'
                        ]);
                    } else {
                        if ($model->errors) return json_encode([
                            'status' => 'error',
                            'message' => "Senha incorreta",
                        ]);
                        else return json_encode([
                            'status' => 'error',
                            'message' => 'Não foi possivel atualizar sua senha.',
                        ]);
                    }
                } else {
                    return $this->renderAjax('resetPassword', [
                        'model' => $model,
                    ]);
                }
            }
            return $this->redirect('/empresa/empresa/perfil');
        } catch (\Exception $e) {
            return json_encode([
                'status' => 'error',
                'message' => $e->getMessage()
            ]);
        }
    }
}

backend/views/users/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'verification_token') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/users/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <div class="row mx-gutters-2">
        <div class="col-md-10">
        <h4 class="font-weight-bold"><?= Html::encode($this->title) ?></h4>
        </div>
        <div class="col-md-2">
            <a class="float-right " href="<?= Url::to(['/users/index'])?>">Voltar</a>
        </div>
    </div>
    <hr>

    <div class="card">
         <div class="card-body shadow-sm p-4">
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
     </div>

</div>

backend/views/users/editar.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;


?>
<div class="user-form">

    <?php $form = ActiveForm::begin([
        'options' => [
           
            'enctype' => 'multipart/form-data',
        ],
    ]); ?>
  
    
    <div class="row mb-5">
        <div class="col-sm-12">
            <label class="label-form">Palavra passe <span class="text-danger">*</span></label>
            <?= $form->field($model, 'password_hash')->passwordInput()->label(false) ?>
        </div>
    </div>
    <div class="row foter mt-2">
        <div class="col-sm-12 text-right">
            <button type="button" class="btn btn-sm rounded btn-soft-secondary transition-3d-hover" data-dismiss="modal" style="margin-right: 5px;"><i class="fa fa-times mr-1"></i><?= Yii::t('app', 'Cancelar') ?></button>
            <?= Html::submitButton($model->isNewRecord ? '<i class="far fa-save mr-2"></i>Guardar' : '<i class="far fa-save mr-2"></i>Guardar', ['class' => $model->isNewRecord ? 'btn btn-indigo btn-sm rounded mr-5' : 'btn btn-indigo btn-sm rounded  mr-5','id'=>'btn-save']) ?>
        </div>
    </div>
<?php ActiveForm::end(); ?>

</div>
<style media="screen">
  
  .foter {
        position: absolute;
        bottom: 1px;
        width: 105%;
        background: white;
    }
</style>

backend/views/users/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
?>
<div class="user-index">
    <div class="row mx-gutters-2">

        <?php if (Yii::$app->session->hasFlash("success-create")): ?>
        <div class="alert-success alert alert-dismissible fade show" role="alert" style="width:100%">
            <?= Yii::$app->session->getFlash("success-create") ?>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <?php endif; ?>
        <?php if (Yii::$app->session->hasFlash("error")): ?>
        <div class="alert-error alert alert-dismissible fade show" role="alert">
            <?= Yii::$app->session->getFlash("error") ?>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <?php endif; ?>

        <div class="col-md-10">
            <h4 class="font-weight-bold">Lista dos Utilizadores</h4>
        </div>
        <div class="col-md-2">
            <!--a class="float-right " href="<!?= Url::to(['/users/index'])?>">Voltar</a-->
        </div>
    </div>
    <hr>

    <table class="table" id="#mySearch-location">
        <thead class="top">
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Tipo de utilizador</th>
                <th scope="col">Opção</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($user as $users):?>
            <tr>
                <td><?= $users->username?></td>
                <td><?= $users->email?></td>
                <td>
                    <?php if($users->type_user == 'admin'):?>
                    Administrador
                    <?php elseif($users->type_user == 'dr'):?>
                    Director
                    <?php elseif($users->type_user == 'Ot'):?>
                    Ortopedista
                    <?php elseif($users->type_user == 'Ft'):?>
                    Fisioterapeuta
                    <?php elseif($users->type_user == 'rp'):?>
                    Recepcionistas
                    <?php elseif($users->type_user == 'as'):?>
                    Asistente social
                    <?php endif;?>

                </td>
                <td>
                    <div class="btn-group position-relative ">
                        <a id="" class="btn btn-sm btn-icon rounded " href="javascript:;" role="button"
                            aria-controls="#id" aria-haspopup="true" aria-expanded="false" data-toggle="dropdown"
                            data-unfold-event="click" data-unfold-target="#" data-unfold-type="css-animation"
                            data-unfold-duration="300" data-unfold-delay="300" data-unfold-animation-in="slideInUp"
                            data-unfold-animation-out="fadeOut" style="width: 2.6rem;">
                            <span class="fas fa-ellipsis-v btn-icon__inner"></span>
                        </a>

                        <div id="" class="dropdown-menu dropdown-unfold dropdown-menu-right"
                            aria-labelledby="id-invoker">

                            <?= Html::a('<i class="fas fa-eye  mr-2"></i> Ver', ['users/view', 'id'=>$users->id], ['class'=>"dropdown-item"])?>
                            <a href="#" class="dropdown-item open-modal" data-modal-size="modal-lg" data-toggle="modal"
                                data-url="<?= Url::to(['users/update', 'id'=>$users->id]) ?>"
                                data-title="<?= Yii::t('app', 'Editar utilizador') ?>">
                                <span class="far fa-edit btn-soft-primary mr-2"></span><?= Yii::t('app', 'Editar') ?>
                            </a>
                            <?= Html::a('<i class="fas fa-trash-alt btn-soft-danger mr-2"></i> Eliminar', ['users/delete', 'id'=>$users->id], ['class'=>"dropdown-item"])?>
                        </div>
                    </div>
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>

backend/views/users/perfil.php
<?php
use \yii\helpers\Url;
?>
<?php
    $this->title = $users->username;
?>
<?php if (Yii::$app->session->hasFlash("success-create")): ?>
<div class="alert-success alert alert-dismissible fade show" role="alert" style="width:100%" >
    <?= Yii::$app->session->getFlash("success-create") ?>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<?php endif; ?>
  <div class="bg-light border shadow-soft rounded p-6 mb-4">
      <div class="media">

          <div class="u-lg-avatar mb-3 mx-auto">
            <?php if (@$users->imagem == '') : ?>
              <img class="w-100 rounded shadow-soft" src="" title="" alt="">
            <?php else : ?>
              <img class="w-100 rounded shadow-soft" src="../../<?= $users->imagem ?>" title="" alt="">
            <?php endif; ?>
          </div>

          <div class="media-body ml-4">
            <div class="mb-3">
                <h4 class=""><?= $users->username ?></h4>
            </div>

              <div class="pb-1 mb-2">
                  <div id="all">
                     
                  </div>

                  
              </div>

              <div class="d-md-flex align-items-md-center">
                      <!-- Location -->
                      <div class="u-ver-divider u-ver-divider--none-md pr-4 mb-3 mb-md-0 mr-4">
                          <h2 class="small text-secondary mb-0">Morada</h2>
                          <small class="fas fa-map-marker-alt text-secondary align-middle mr-1"></small>
                          <span class="align-middle"><?=$users->morada?></span>
                      </div>
                      <!-- End Location -->

                      <!-- Posted -->
                      <div class="u-ver-divider u-ver-divider--none-md pr-4 mb-3 mb-md-0 mr-4">
                          <h3 class="small text-secondary mb-0">Contacto</h3>
                          <small class="fas fa-phone text-secondary align-middle mr-1"></small>
                          <span class="align-middle"><?=$users->contacto?></span>
                      </div>
                      <!-- End Posted -->
                      <!-- Posted -->
                      <div class="mb-3 mb-md-0">
                          <h5 class="small text-secondary mb-0">Email</h5>
                          <small class="fas fa-envelope text-secondary align-middle mr-1"></small>
                          <span class="align-middle"><?=$users->email?></span>
                      </div>
                      <!-- End Posted -->
                  </div>
          </div>

         
             <!-- End Settings -->

              <div class="mb-0">

              </div>
              <div class="media align-items-center text-right">
                <div class="ml-md-auto">
                  <!-- Settings -->
                  <div class="position-relative mb-3">
                    <a id="settingsDropdown1InvokerExample1" class="btn btn-sm btn-soft-secondary rounded" href="javascript:;" role="button"
                        aria-controls="settingsDropdown1"
                        aria-haspopup="true"
                        aria-expanded="false"
                        data-unfold-event="click"
                        data-unfold-target="#settingsDropdown1"
                        data-unfold-type="css-animation"
                        data-unfold-duration="300"
                        data-unfold-delay="300"
                        data-unfold-hide-on-scroll="true"
                        data-unfold-animation-in="slideInUp"
                        data-unfold-animation-out="fadeOut">
                      Editar<span class="fas fa-sort-down ml-2"></span>
                    </a>

                    <div id="settingsDropdown1" class="dropdown-menu dropdown-unfold dropdown-menu-right" aria-labelledby="settingsDropdown1InvokerExample1" style="min-width: 160px;">
                      <a class="dropdown-item open-modal" href="javascript:void(0)"
                          data-url="<?= Url::to(['/users/updates', 'id'=>$users->id])?>" data-toggle="modal" data-modal-size="modal-lg" data-title="Ediatr perfil">
                          <small class="fas fa-user-tag dropdown-item-icon"></small>
                          Perfil
                      </a>
                      <a class="dropdown-item " href="<?= Url::to(['/users/difinicao'])?>"
                           >
                          <small class="fas fa-key dropdown-item-icon"></small>
                          Palavra passe
                      </a>

                    </div>
                  </div>
                </div>
              </div>
      </div>
</div>

<script>
  $(function(){
    $.HSCore.components.HSUnfold.init($('[data-unfold-target]'));
  });
</script>
<?php

$script = <<<JS

        $(document).on('click', '.all', function (e) {
            e.preventDefault();
            $('#all').attr('style', 'display: none;');
            $('#less').attr('style', 'display: block;');
        });

        $(document).on('click', '.less', function (e) {
            e.preventDefault();
            $('#all').attr('style', 'display: block;');
            $('#less').attr('style', 'display: none;');
        });
JS;
$this->registerJS($script);
?>

backend/views/users/update.php
<?php

use yii\helpers\Html;
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/users/view.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
$this->title = $model->username;
\yii\web\YiiAsset::register($this);
?>
<div class="user-view">
     <div class="row">
         <div class="col-sm-6 ">
            <h1><?= Html::encode($this->title) ?></h1>
         </div>
         <div class="col-sm-6 text-right">
             <a class="" href="<?= Url::to(['/users'])?>">Voltar</a>
         </div>
     </div>
    <hr>
    <div class="card mb-2">
        <div class="card-body">
            <!-- Header -->
            <div class="media align-items-center mb-4">
                <!-- Avatar -->
                <div class="u-xl-avatar mr-4">
                    <img class="w-100 h-100 shadow-soft rounded-circle mx-auto" src="../../<?= @$model->imagem?>">
                </div>
                <!-- End Avatar -->
                <div class="media-body">
                    <h1 class="font-weight-bold h4">
                        <?= $model->username?>
                     </h1>

                    <p><?= $model->email?></p>
                    <!--small class="text-secondary"></small-->

                    <div class="card-footer border-top-0 pt-3 px-0 pb-4">
                        <div class="d-sm-flex align-items-sm-center">
                            <?php if($model->created_at):?>
                                <div class="u-ver-divider u-ver-divider--none-sm pr-4 mr-4 mb-3 mb-sm-0">
                                    <h2 class="small text-secondary mb-0">Data</h2>
                                    <small class="fas fa-calendar-alt text-secondary mr-1" aria-hidden="true"></small>
                                    <span class="align-middle font-size-1 font-weight-medium"><?= $model->created_at?> </span>
                                </div>
                            <?php endif;?>
                            <?php if($model->contacto):?>
                                <div class="u-ver-divider u-ver-divider--none-sm pr-4 mr-4 mb-3 mb-sm-0">
                                    <h2 class="small text-secondary mb-0">Contacto</h2>
                                    <small class="fas fa-calendar-alt text-secondary mr-1" aria-hidden="true"></small>
                                    <span class="align-middle font-size-1 font-weight-medium"><?= $model->contacto?> </span>
                                </div>
                            <?php endif;?>
                            <?php if($model->type_user):?>
                                <div class="u-ver-divider u-ver-divider--none-sm pr-4 mr-4 mb-3 mb-sm-0">
                                    <h2 class="small text-secondary mb-0">Tipo de utilizador</h2>
                                    <small class="fas fa-calendar-alt text-secondary mr-1" aria-hidden="true"></small>
                                    <span class="align-middle font-size-1 font-weight-medium">
                                        <?php if($model->type_user == 'admin'):?>
                                        Administrador
                                        <?php elseif($model->type_user == 'dr'):?>
                                        Director
                                        <?php elseif($model->type_user == 'Ot'):?>
                                        Ortopedista
                                        <?php elseif($model->type_user == 'Ft'):?>
                                        Fisioterapeuta
                                        <?php elseif($model->type_user == 'rp'):?>
                                        Recepcionistas
                                        <?php elseif($model->type_user == 'as'):?>
                                        Asistente social
                                        <?php endif;?>
                                    </span>
                                </div>
                            <?php endif;?>
                      
                            <!-- Review -->
                            <div class="ml-md-auto">
                                <a href="#" class="btn btn-soft-primary rounded btn-sm open-modal" data-modal-size="modal-lg" data-toggle="modal"
                                    data-url="<?= Url::to(['users/update', 'id'=>$model->id]) ?>"
                                    data-title="<?= Yii::t('app', 'Editar utilizador') ?>">
                                    <span class="fas fa-pencil-alt dropdown-item-icon mr-2"></span><?= Yii::t('app', 'Editar') ?>
                                </a>
                                <?= Html::a('<i class="fas fa-trash-alt btn-soft-danger mr-2"></i> Eliminar', ['users/delete', 'id'=>$model->id], ['class'=>"btn btn-sm btn-outline-danger rounded"])?>
                            </div>
                            <!-- End Review -->

                        </div>
                    </div>

                </div>
            </div>
            <!-- End Header -->
        </div>

    </div>



</div>